# Generated by Django 4.2.23 on 2025-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="iamge",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
