# Generated by Django 4.2.23 on 2025-08-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/profile/default.jpg', upload_to='profile_images/'),
        ),
    ]
