# Generated by Django 4.2.23 on 2025-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profile_images/profile/default.png",
                upload_to="profile_images/",
            ),
        ),
    ]
