# Generated by Django 4.2.23 on 2025-07-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
