# Generated by Django 4.2.23 on 2025-07-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_productmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategorymodel",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
