# Generated by Django 4.2.23 on 2025-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_wishlistproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='avg',
            field=models.FloatField(default=0.0),
        ),
    ]
