# Generated by Django 4.2.23 on 2025-10-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="couponmodel",
            old_name="expiry_date",
            new_name="expiration_date",
        ),
    ]
