# Generated by Django 4.2.23 on 2025-10-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
        ("order", "0002_rename_expiry_date_couponmodel_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.paymentmodel",
            ),
        ),
    ]
