# Generated by Django 4.2.23 on 2025-10-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_ordermodel_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.IntegerField(
                choices=[(1, "در انتظار پرداخت"), (2, "در حال پردازش"), (5, "لغو شده")],
                default=1,
            ),
        ),
    ]
