# Generated by Django 4.2.23 on 2025-10-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_ordermodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.IntegerField(
                choices=[(1, "در انتظار پرداخت"), (2, "موفقیت آمیز"), (3, "لغو شده")],
                default=1,
            ),
        ),
    ]
